import { Category, Product } from "./types";

export const catagorys: Category[] = [
  {
    id: 1,
    name: "Electronics",
    image: "https://source.unsplash.com/random/400x400?electronics",
  },
  {
    id: 2,
    name: "Clothing",
    image: "https://source.unsplash.com/random/400x400?clothing",
  },
  {
    id: 3,
    name: "Home Decor",
    image: "https://source.unsplash.com/random/400x400?home-decor",
  },
];

export const products: Product[] = [
  {
    id: 5,
    categoryId: 1,
    name: "Wireless Headphones",
    price: 79.99,
    rating: 4.5,
  },
  {
    id: 6,
    categoryId: 1,
    name: "Bluetooth Speaker",
    price: 49.99,
    rating: 4.2,
  },
  { id: 7, categoryId: 1, name: "USB-C Hub", price: 29.99, rating: 4.0 },
  { id: 8, categoryId: 2, name: "Classic T-Shirt", price: 19.99, rating: 4.3 },
  { id: 9, categoryId: 2, name: "Denim Jacket", price: 59.99, rating: 4.6 },
  { id: 10, categoryId: 2, name: "Sneakers", price: 89.99, rating: 4.7 },
  { id: 11, categoryId: 3, name: "Scented Candle", price: 14.99, rating: 4.2 },
  { id: 12, categoryId: 3, name: "Wall Clock", price: 34.99, rating: 4.1 },
  { id: 13, categoryId: 3, name: "Throw Pillow", price: 24.99, rating: 4.3 },
  { id: 14, categoryId: 1, name: "Smart Watch", price: 129.99, rating: 4.8 },
  { id: 15, categoryId: 2, name: "Leather Belt", price: 24.99, rating: 4.1 },
  { id: 16, categoryId: 3, name: "Desk Lamp", price: 39.99, rating: 4.4 },
  {
    id: 17,
    categoryId: 1,
    name: "Mechanical Keyboard",
    price: 109.99,
    rating: 4.6,
  },
  { id: 18, categoryId: 1, name: "Gaming Mouse", price: 59.99, rating: 4.5 },
  { id: 19, categoryId: 1, name: "Webcam HD", price: 74.99, rating: 4.3 },
  { id: 20, categoryId: 1, name: "Monitor Stand", price: 44.99, rating: 4.2 },
  { id: 21, categoryId: 1, name: "Laptop Sleeve", price: 19.99, rating: 4.0 },
  {
    id: 22,
    categoryId: 1,
    name: "Portable Charger",
    price: 34.99,
    rating: 4.4,
  },
  {
    id: 23,
    categoryId: 1,
    name: "Noise Cancelling Earbuds",
    price: 89.99,
    rating: 4.7,
  },
  { id: 24, categoryId: 2, name: "Graphic Tee", price: 22.99, rating: 4.2 },
  { id: 25, categoryId: 2, name: "Chino Pants", price: 49.99, rating: 4.3 },
  { id: 26, categoryId: 2, name: "Hoodie", price: 54.99, rating: 4.5 },
  { id: 27, categoryId: 2, name: "Baseball Cap", price: 17.99, rating: 4.1 },
  { id: 28, categoryId: 2, name: "Running Shorts", price: 29.99, rating: 4.0 },
  { id: 29, categoryId: 2, name: "Wool Scarf", price: 34.99, rating: 4.4 },
  { id: 30, categoryId: 3, name: "Bookshelf", price: 89.99, rating: 4.3 },
  {
    id: 31,
    categoryId: 3,
    name: "Indoor Plant Pot",
    price: 19.99,
    rating: 4.2,
  },
  { id: 32, categoryId: 3, name: "Picture Frame", price: 14.99, rating: 4.0 },
  {
    id: 33,
    categoryId: 3,
    name: "Decorative Mirror",
    price: 64.99,
    rating: 4.5,
  },
  { id: 34, categoryId: 3, name: "Cozy Blanket", price: 44.99, rating: 4.6 },
  { id: 35, categoryId: 3, name: "Bathroom Rug", price: 24.99, rating: 4.1 },
  {
    id: 36,
    categoryId: 3,
    name: "Candle Holder Set",
    price: 29.99,
    rating: 4.3,
  },
];
